
import { project } from "../app/types/project";

export const HospitalItems: project[] = [
  {
    id: 1,
    category: "hospital",
    title: "Hospital Management",
    description: "Hospital Login",
    image: "assets/img/10.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "hospital",
    title: "Patient Registration",
    description: "New Patient Registration",
    image: "assets/img/7.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "hospital",
    title: "Patient List",
    description: "All Patient List",
    image: "assets/img/9.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "hospital",
    title: "Medicine",
    description: "List of All Medicine  ",
    image: "assets/img/8.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "hospital",
    title: "X-Ray",
    description: "Patient x-ray reports ",
    image: "assets/img/6.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "hospital",
    title: "Payment",
    description: "Payment Pannel",
    image: "assets/img/5.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "hospital",
    title: "Patient By Serial No.",
    description: "Find By SerialNo.  ",
    image: "assets/img/4.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "hospital",
    title: "Loan Application.",
    description: "Apply Loan App",
    image: "assets/img/3.png",
    detailsLink: "Link",
  },
  // {
  //   id: 9,
  //   category: "Product",
  //   title: "Dashboard",
  //   description: "Hospital Dashboard",
  //   image: "assets/img/2.png",
  //   detailsLink: "Link",
  // },
];

export const ApiGroup: project[] = [
  {
    id: 1,
    category: "Apis",
    title: "Threejs 3D",
    description: "Planets",
    image: "assets/img/three1.png",
    detailsLink: "https://solar-system-threejs-one.vercel.app/",
  },
  {
    id: 2,
    category: "Apis",
    title: "Around The World",
    description: "Earth",
    image: "assets/img/threeimg.png",
    detailsLink: "https://solar-system-threejs-one.vercel.app/",
  },
  {
    id: 3,
    category: "Apis",
    title: "Threejs 3D",
    description: "Water ",
    image: "assets/img/threeimg2.png",
    detailsLink: "https://solar-system-threejs-one.vercel.app/",
  },
  {
    id: 4,
    category: "Apis",
    title: "ChatBot",
    description: "Gemini Chatbot  ",
    image: "assets/img/chat.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "Apis",
    title: "Test CDN",
    description: "CDN",
    image: "assets/img/mycdn.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "Apis",
    title: "Google Dev",
    description: "Search Engine",
    image: "assets/img/google.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "Apis",
    title: "TikTokToe",
    description: "ReactJsTikTokToe",
    image: "assets/img/tiktok.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "Apis",
    title: "My CDN.",
    description: "Css,Js,CDN",
    image: "assets/img/testcdn.png",
    detailsLink: "Link",
  },
];

export const ApiUserAdminItems: project[] = [
  {
    id: 1,
    category: "Api",
    title: "Api Admin",  
    description: "Admin Dashbord",
    image: "assets/img/admindash.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "Api",
    title: "Api Admin",
    description: "Admin Fund Approve",
    image: "assets/img/adminFApprove.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "Api",
    title: "Api Admin",
    description: "Adnin Pin & Ipaddress",
    image: "assets/img/adminPin.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "Api",
    title: "Api User",
    description: "User Dashboard",
    image: "assets/img/userdashprofile.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "Api",
    title: "Api User",
    description: "Digital KYC ",
    image: "assets/img/digitalKYC.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "Api",
    title: "Api User",
    description: "User HelpDesk",
    image: "assets/img/userHelpDesk.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "Api",
    title: "Api User",
    description: "User Mobile View",
    image: "assets/img/userMobDash.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "Api",
    title: "Api User",
    description: "User Test Aadhar",
    image: "assets/img/userTestAadhar.png",
    detailsLink: "Link",
  },
  {
    id: 9,
    category: "Api",
    title: "Api User",
    description: "User Test Pan",
    image: "assets/img/userTestPan.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Test Crif",
    image: "assets/img/userHighmarkscore.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Test Equifax",
    image: "assets/img/userEquifaxScore.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Lock Screen",
    image: "assets/img/userLock.png",
    detailsLink: "Link",
  },
];

export const HotelItems: project[] = [
  {
    id: 1,
    category: "Hotel",
    title: "Register",
    description: "User Register",
    image: "assets/img/Yad7.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 2,
    category: "Hotel",
    title: "Login",
    description: "Customer Login",
    image: "assets/img/Yad6.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 3,
    category: "Hotel",
    title: "Hotal List",
    description: "All Hotal",
    image: "assets/img/Yad5.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 4,
    category: "Hotel",
    title: "Event List",
    description: "Event List",
    image: "assets/img/Yad4.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 5,
    category: "Hotel",
    title: "Theme Explore",
    description: "Theme Explore ",
    image: "assets/img/Yad3.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 6,
    category: "Hotel",
    title: "Nearby Hotel",
    description: "Nearby Hotel",
    image: "assets/img/Yad2.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 7,
    category: "Hotel",
    title: "Search A/q Hotel",
    description: "Search Hotel.",
    image: "assets/img/Yad1.png",
    detailsLink: "https://www.yaadgarpal.com/",
  },
  {
    id: 8,
    category: "Hotel",
    title: "Mobile View",
    description: "Hotel Login",
    image: "assets/img/Yad8.png",
    detailsLink: "https://www.yaadgarpal.com/",
  }
];      